<?php

namespace DoctrineORMModule\Proxy\__CG__\RecipayAdmin\Infra\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \RecipayAdmin\Infra\Entity\Product implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'name', 'image', 'textinstruction', 'recipevideo', '' . "\0" . 'RecipayAdmin\\Infra\\Entity\\Product' . "\0" . 'date', '' . "\0" . 'RecipayAdmin\\Infra\\Entity\\Product' . "\0" . 'menu', '' . "\0" . 'RecipayAdmin\\Infra\\Entity\\Product' . "\0" . 'category', 'baseprice', 'pax', 'sales_count', 'stock', 'restock', 'replenish'];
        }

        return ['__isInitialized__', 'id', 'name', 'image', 'textinstruction', 'recipevideo', '' . "\0" . 'RecipayAdmin\\Infra\\Entity\\Product' . "\0" . 'date', '' . "\0" . 'RecipayAdmin\\Infra\\Entity\\Product' . "\0" . 'menu', '' . "\0" . 'RecipayAdmin\\Infra\\Entity\\Product' . "\0" . 'category', 'baseprice', 'pax', 'sales_count', 'stock', 'restock', 'replenish'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Product $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage(string $image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getTextinstruction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTextinstruction', []);

        return parent::getTextinstruction();
    }

    /**
     * {@inheritDoc}
     */
    public function setTextinstruction(string $textinstruction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTextinstruction', [$textinstruction]);

        return parent::setTextinstruction($textinstruction);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecipevideo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecipevideo', []);

        return parent::getRecipevideo();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecipevideo(string $recipevideo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecipevideo', [$recipevideo]);

        return parent::setRecipevideo($recipevideo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getMenu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMenu', []);

        return parent::getMenu();
    }

    /**
     * {@inheritDoc}
     */
    public function setMenu(\RecipayAdmin\Infra\Entity\Menu $menu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMenu', [$menu]);

        return parent::setMenu($menu);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', []);

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory(\RecipayAdmin\Infra\Entity\Category $category)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', [$category]);

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getBaseprice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBaseprice', []);

        return parent::getBaseprice();
    }

    /**
     * {@inheritDoc}
     */
    public function setBaseprice($baseprice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBaseprice', [$baseprice]);

        return parent::setBaseprice($baseprice);
    }

    /**
     * {@inheritDoc}
     */
    public function getPax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPax', []);

        return parent::getPax();
    }

    /**
     * {@inheritDoc}
     */
    public function setPax($pax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPax', [$pax]);

        return parent::setPax($pax);
    }

    /**
     * {@inheritDoc}
     */
    public function getSales_count()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSales_count', []);

        return parent::getSales_count();
    }

    /**
     * {@inheritDoc}
     */
    public function setSales_count($sales_count)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSales_count', [$sales_count]);

        return parent::setSales_count($sales_count);
    }

    /**
     * {@inheritDoc}
     */
    public function getStock()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStock', []);

        return parent::getStock();
    }

    /**
     * {@inheritDoc}
     */
    public function setStock($stock)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStock', [$stock]);

        return parent::setStock($stock);
    }

    /**
     * {@inheritDoc}
     */
    public function getRestock()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRestock', []);

        return parent::getRestock();
    }

    /**
     * {@inheritDoc}
     */
    public function setRestock($restock)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRestock', [$restock]);

        return parent::setRestock($restock);
    }

    /**
     * {@inheritDoc}
     */
    public function getReplenish()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReplenish', []);

        return parent::getReplenish();
    }

    /**
     * {@inheritDoc}
     */
    public function setReplenish($replenish)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReplenish', [$replenish]);

        return parent::setReplenish($replenish);
    }

}
